baseURL: "https://caldwellwg.github.io/" 
title: Wes Caldwell
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Wes Caldwell's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Wes Caldwell
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Wes Caldwell
          subtitle: "I am a postdoc in the Johns Hopkins University (JHU) Applied Mathematics & Statistics Department, currently working in the Applied and Computational Mathematics Division of the National Institute of Standards and Technology (NIST). My research focuses on the calculus of variations with applications in materials science. I received my Ph.D. at Carnegie Mellon University in 2025 under the direction of Professors Irene Fonseca & Giovanni Leoni."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Talks
              url: talks/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:wcaldwe6@jh.edu
        - name: ORCID
          url: https://orcid.org/0009-0002-9874-2821
        - name: GitHub
          url: https://github.com/caldwellwg

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Wes Caldwell"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
